---
- hosts: localhost
  become: yes
  tasks:
    - name: Set up home server
      include_tasks: "{{ item }}"
      loop:
        - duckdns.yml
        - fail2ban.yml
        - ssh.yml
        - wireguard.yml
